[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "universal_meteo_analyzer"
version = "1.0.0"
authors = [ {  name="Халкаліс О. Ф.", email="chalkalisolga@gmail.com" } ]
description = "Універсальний консольний застосунок для збору метеорологічних даних у будь-якій точці світу"
readme = "README.md"
requires-python = ">=3.10"